### ISSUE TITLE
import Gzip failed - no such module

### ISSUE THREAD

**Issue by Geeo** [1024jp/GzipSwift#10]
Hi,

I've :
- downloaded the latest version
- build it (Gzip-iOS target)
- copy the Gzip.framework to my project
- added Gzip.framework to Link Binary With Libraries

And import doesn't work.

Did I miss something ?

**Comment by Geeo** [comment]
Ok i've figured it out, you can close the ticket, sorry !
(I think that i've taken the wrong Gzip.framework from build directory)

**Comment by 1024jp** [comment]
n.p.
Ok, I close this issue.

**Comment by sonamsamdupkhangsar** [comment]
Hi,
I followed your instruction to add to "Embedded Binaries" but I still get the "No such module 'Gzip'" error.  
There were several Gzip.framework under "Products" folder.  I picked one which was not highlighted in red font.  I copied it to my project and I can expand it to see a "Headers" folder with Gzip-Swift.h file.   Do I need to pick another file instead?

thanks
-Sonam
