### ISSUE TITLE
CocoaPods installation - [!] Unable to find a specification for `GzipSwift`

### ISSUE THREAD

**Issue by Rashidium** [1024jp/GzipSwift#11]
As you mentioned in Readme file:

`pod "GzipSwift"`

After calling "pod install" in terminal:

> [!] Unable to find a specification for `GzipSwift`

**Comment by 1024jp** [comment]
If you use CocoaPods first time, you need to run `pod setup` on your Terminal. Then, run `pod install` again.

**Comment by Rashidium** [comment]
If I hadn't installed CocoaPods I would receive "no command pods" instead of 
> [!] Unable to find a specification for GzipSwift
I can use other pods but not GzipSwift.

**Comment by Rashidium** [comment]
Not sure how, but I could integrate it now. Thanks for your time.

**Comment by 1024jp** [comment]
Oh sorry, cause the error was specific when users just installed CocoaPods but not yet setup. 
But anyway, it's good it works now.
