### ISSUE TITLE
Cant find Zlib

### ISSUE THREAD

**Issue by HPRaval** [1024jp/GzipSwift#12]
I have used your library using pod, but it gives me bunch of errors and can't find Error, data etc.

**Comment by 1024jp** [comment]
There is too less information.
Tell me what you did and the error log you obtained.

**Comment by caiodias** [comment]
Probably he only copied the swift file and didn't pay attention on the module folder

**Comment by 1024jp** [comment]
I close this issue due to no reply. Reopen if you have another comment.
