### ISSUE TITLE
Xcode9-Bata2 error

### ISSUE THREAD

**Issue by gityoung** [1024jp/GzipSwift#15]
<img width="273" alt="2017-07-07 6 15 09" src="https://user-images.githubusercontent.com/9583031/27953930-4e4cbafe-62d3-11e7-9d62-444b5da71576.png">
<img width="643" alt="2017-07-07 6 15 22" src="https://user-images.githubusercontent.com/9583031/27953932-4f0e13fc-62d3-11e7-8aa1-f624b3623192.png">

**Comment by 1024jp** [comment]
Which branch and which tareget did you try?
I made swift4 branch for the upcoming Xcode 9.
And with this swift4 branch + Xcode9-beta.2, I don't get any error under my environment.

**Comment by 1024jp** [comment]
No update?
If so, I'd close this issue.
