### ISSUE TITLE
Can I use CocoaPods with swift4

### ISSUE THREAD

**Issue by juangamnik** [1024jp/GzipSwift#17]
The readme on the "swift4"-branch says the same config as for "develop"-branch (using cocoa pods). Does this work or do I have to build manually? Thank you very much in advance.

**Comment by juangamnik** [comment]
found it in #14:

`pod 'GzipSwift', :git => 'https://github.com/1024jp/GzipSwift.git', :branch => 'swift4'`

Perhaps it is worth adding this to the readme on the branch?

**Comment by 1024jp** [comment]
I thought it's not important to add installation instructions for the branch.
But it seems better to do.
Thanks.

**Comment by juangamnik** [comment]
Thank **you** for the work on this project!
