### ISSUE TITLE
Introduce CocoaPods

### ISSUE THREAD

**Issue by 1024jp** [1024jp/GzipSwift#2]
Create podspec and register it.

**Comment by 1024jp** [comment]
I suppose CocoaPods 0.37 doesn't support Swift with C libraries enough well.
It's better to wait for the upcoming versions with better Swift support.

**Comment by ninokierulf** [comment]
bump

**Comment by Geeo** [comment]
What about now ?

**Comment by 1024jp** [comment]
Still pending.
Honestly, I don't use CocoaPods personally anymore. So, the priority for me is now relatively low.
But well, recently, CocoaPods became 1.0. It's worth a try again.

**Comment by 1024jp** [comment]
I've just registered my GzipSwift to CocoaPods 😉.

```ruby
pod 'GzipSwift'
```

Feel free to create another issue if it doesn't work correctly.
