### ISSUE TITLE
Gather Coverage Data should be disabled in default scheme

### ISSUE THREAD

**Issue by danielsegall** [1024jp/GzipSwift#21]
Xcode 9 now builds the same binary for build, test and run, and will therefore apps submitted using a framework built with coverage enabled are rejected by Apple for including tooling in the build settings.

Please disable code coverage so that default Carthage builds can be submitted to the App Store.

**Comment by 1024jp** [comment]
I've just released GzipSwift 4.0.1 with this fix.
Does it work?

**Comment by danielsegall** [comment]
Seems to be as expected, thanks.
