### ISSUE TITLE
Build fails with v4.0.3

### ISSUE THREAD

**Issue by SlamGrooveFE** [1024jp/GzipSwift#25]
Installed v4.0.3 via CocoaPods: 
pod 'GzipSwift', :git => 'https://github.com/1024jp/GzipSwift.git', :tag => '4.0.3'

Project build fails:
"No such module 'Gzip'"

![screen shot 2017-11-12 at 15 01 00](https://user-images.githubusercontent.com/5112650/32699233-0011e420-c7bb-11e7-9ad6-bb2274c7db54.png)

These are the contents of GzipSwift pod folder after `pod install/update`:
![screen shot 2017-11-12 at 15 01 52](https://user-images.githubusercontent.com/5112650/32699244-159911ba-c7bb-11e7-99f8-ca439e0bc8fe.png)
 
Xcode 9.1

**Comment by 1024jp** [comment]
I've just released 4.0.4. Does the matter fixed?

**Comment by SlamGrooveFE** [comment]
Yes, version 4.0.4 works perfectly!! 
Thanks for a quick response. 👍

**Comment by 1024jp** [comment]
@SlamGrooveFE Thank you for the reply. It's glad to hear.
