### ISSUE TITLE
cannot use in OC project 

### ISSUE THREAD

**Issue by chunxigege** [1024jp/GzipSwift#26]

**Comment by 1024jp** [comment]
What's the OC project? Objective-C?

**Comment by chunxigege** [comment]
yes , I  import the framework in Objective-C project, it cannot use

**Comment by 1024jp** [comment]
As the name represents, GzipSwift is for Swift.
Therefore, I don't recommend to use GzipSwift in ObjC project.

However, if you yet want to use GzipSwift in Objective-C for some reason,
You need to add a bridge code to use Swift.Data methods in NSData, something like this:

```swift
import Gzip

public extension NSData {
    
    @objc func gunzippedData() -> NSData? {
        
        return (try? (self as Data).gunzipped()) as NSData?
    }
    
    
    @objc func gzippedData() -> NSData? {
        
        return (try? (self as Data).gzipped()) as NSData?
    }
}
```
