### ISSUE TITLE
Swift 3 branch?

### ISSUE THREAD

**Issue by TarekSalama** [1024jp/GzipSwift#27]
Hello,

I'm using Carthage. Is there a Swift 3 branch since the project I'm working on uses Swift 3?

Thanks

**Comment by 1024jp** [comment]
There is no Swift 3 branch.
`3.1.4` tag is the latest version for Swift 3. However, I'm not sure if it works with Swift 3.2 + Xcode 9.1... Well, please try it first.

**Comment by TarekSalama** [comment]
Yes I'm using 3.2 and Xcode 9.1

I'm getting this error `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by TarekSalama** [comment]
Ok so I tried creating a new project and I changed its language to 3.2. It compiled perfectly.
Eventually I found out that the clang error could be fixed by deleted the derived data folder in Xcode.
Sorry for the false report :) Thanks for the library by the way it's a life saver.

**Comment by 1024jp** [comment]
Oh, that's good to hear.
Thanks for the follow-up.
