### ISSUE TITLE
Gzip extension not linking

### ISSUE THREAD

**Issue by randymelder** [1024jp/GzipSwift#28]
Getting Swift errors trying to access extension after:

- Embedded Binary (see attached)
- Linked Framework (see attached)
- Import Gzip (at top of swift file)

Value of type 'Data' has no member 'isGzipped' ... etc.

I guess I should add, this is a mixed Objective-c / Swift project.

<img width="540" alt="screen shot 2018-01-25 at 9 10 59 am" src="https://user-images.githubusercontent.com/857124/35401995-0cc1e3a8-01b0-11e8-8f05-5634599562cc.png">
<img width="833" alt="screen shot 2018-01-25 at 9 09 56 am" src="https://user-images.githubusercontent.com/857124/35402004-1230a996-01b0-11e8-927e-c0f316ceff23.png">

**Comment by Armax** [comment]
@randymelder I found a solution for my case, remove the Gzip framework from the project, close it, and reinstall Gzip framework using Pod

**Comment by 1024jp** [comment]
This issue was closed because it has been inactive for years since the last update and may be outdated. Please post a new comment if you still have an issue.
