### ISSUE TITLE
Missing magic number after compress

### ISSUE THREAD

**Issue by RonGafni** [1024jp/GzipSwift#29]
Hey.

I need to send encoded url compress string with GET Request. 

I try to compress the data and it work, but I have dont have the magic number at the beginning. 

This is my compress string:
H4sIAAAAAAACE6vmUlBQMlZSsFKIBrKAbEMTCzMzY0slHQTX3MRYCciL5aoFAN6CsvEuAAAA

In my android app this is the compress string I send:  

UwAAAB+LCAAAAAAAAACrVjJUsopWMjQ1NDE2NlHSgbLMQCwTE3NTQws4CyZmYolgWSrF6igZg00w
sTA3MgPyawFa5z/eUwAAAA==

Its not the same but you can see the diffrent in the beginning with the magic number.

I dont data.gzipped() and also try all the compress options.

What can I do?

Thanks!

**Comment by 1024jp** [comment]
This issue was closed because it has been inactive for years since the last update and may be outdated. Please post a new comment if you still have an issue.
