### ISSUE TITLE
"No framework found Gzip"

### ISSUE THREAD

**Issue by PrajaktaSonawane5** [1024jp/GzipSwift#31]
While manually integration getting linker command failed with exit code 1 (use -v to see invocation) "no framework found issue" 
and on pod integration while import Gzip getting "No such module Gzip" issue.

**Comment by tamutti** [comment]
I had this problem as well. You have to tell the app to build. After that the error went away. The framework has a problem somewhere in that it is not built yet.

**Comment by adamwaite** [comment]
You need to `import GzipSwift` I think.

**Comment by zorro0799** [comment]
I have the same problem, but I can't install it with pod

**Comment by 1024jp** [comment]
This issue was closed because it has been inactive for years since the last update and may be outdated. CocoaPods is no more supported for GzipSwift.
