### ISSUE TITLE
Unsaferawbufferpointer is not convertible to Unsafepointer

### ISSUE THREAD

**Issue by hytaoist** [1024jp/GzipSwift#36]
some error appeared when i use GzipSwift in swift 4.2. 
like:
`           self.withUnsafeBytes { (inputPointer: UnsafeRawBufferPointer) in
                stream.next_in = UnsafeMutablePointer<Bytef>(mutating: inputPointer.bindMemory(to: Bytef.self).baseAddress!).advanced(by: Int(stream.total_in))
                stream.avail_in = uint(inputCount) - uInt(stream.total_in)
                
                data.withUnsafeMutableBytes { (outputPointer: UnsafeMutableRawBufferPointer) in
                    stream.next_out = outputPointer.bindMemory(to: Bytef.self).baseAddress!.advanced(by: Int(stream.total_out))
                    stream.avail_out = uInt(outputCount) - uInt(stream.total_out)
                    
                    status = deflate(&stream, Z_FINISH)
                    
                    stream.next_out = nil
                }
                
                stream.next_in = nil
            }`
anyone has a idea?

**Comment by 1024jp** [comment]
Please use not the latest one but one with tag 4.1.0.

**Comment by yzhong52** [comment]
@1024jp 4.1.0 is for Swift 5 right? By any chance can we bring this fix back to 4.2 branches/releases as well?
