### ISSUE TITLE
gzipping creates data which is not unzipable

### ISSUE THREAD

**Issue by Vario** [1024jp/GzipSwift#40]
Since Swift 5 the zipped data cannot be unziped again, even not in Finder.

When extracting not via API, the result is a file with name: origname.gz.cpgz

Extracting via API results in an empty String.
Compressed was a String with utf8 enconding.

**Comment by bellebethcooper** [comment]
I'm having this issue as well, and when trying to unzip using Terminal, I get this error:

```
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

**Comment by grEvenX** [comment]
@bellebethcooper @Vario Are you sure you were using version 5.0.0 of the GzipSwift library when you got this error? We are experiencing the same, but didn't update to 5.0.0 yet (which we will try tomorrow).

**Comment by bellebethcooper** [comment]
> @bellebethcooper @Vario Are you sure you were using version 5.0.0 of the GzipSwift library when you got this error? We are experiencing the same, but didn't update to 5.0.0 yet (which we will try tomorrow).

I haven't tried 5.0. I tried 4.1 and older versions. I'm using Swift 4.2, not Swift 5.

**Comment by nik6018** [comment]
I am using swift 4 and currently on ver 5.0.0 of GzipSWift and getting the following error when I try to unzip the zipped data :
`Gzip.GzipError.Kind.data, message: "unknown compression method")`
This issue started when I upgraded to Xcode 10.2.1, it was working fine on Xcode 10.1

**Comment by grEvenX** [comment]
For the record, we updated to 5.0.0 and are using it together with Swift 5 / XCode 10.2.1 and haven't seen any issues after upgrading to that 👍

**Comment by bellebethcooper** [comment]
@grEvenX Thanks for the update! I've just migrated to Swift 5 so I'll update to 5.0.0 and try it soon.

**Comment by bellebethcooper** [comment]
@grEvenX After migrating to Swift 5 and installing 5.0.0 of GzipSwift I'm not having issues anymore either 👍
