### ISSUE TITLE
DataSize.chunk incorrect

### ISSUE THREAD

**Issue by MorrisRH** [1024jp/GzipSwift#41]
DataSize.chunk is currently 2 ^ 14 which is a value of 12 (^ is the XOR operator), not the intended value of 16384.
Changing this to 1 << 14 solved an issue where data compressed with .gzipped() wouldn't decompress with .gunzipped().

**Comment by 1024jp** [comment]
Thank you for pointing it out!
I've fixed it in v5.1.0.
