### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by LucasMW** [1024jp/GzipSwift#45]
crashes at line  `deflate(&stream, Z_FINISH)`
<img width="428" alt="Screen Shot 2019-12-04 at 2 12 56 PM" src="https://user-images.githubusercontent.com/8429832/70164580-2f28c180-16a0-11ea-910e-6d02a695b7ef.png">
on usage like this:
`let compressed = try! self.gzipped()`
No idea why

**Comment by scottymac** [comment]
I'm seeing this as well.

**Comment by LucasMW** [comment]
I removed the pod; and installed it again;
It stopped;
Guess it was some kind of leftovers in a wrong swift version. I don't know

**Comment by 1024jp** [comment]
I closed this issue as it seems to be solved already.
