### ISSUE TITLE
Xcode 12 :  Unsigned code error when trying to run on iOS

### ISSUE THREAD

**Issue by gangadharbonda** [1024jp/GzipSwift#48]
Currently, I am using GZip framework in my sub-project and when running the application I see the following error

/PlugIns/MobiConnect-iOSUITests.xctest/Frameworks/MobiCore.framework/Frameworks/Gzip.framework/Gzip) **not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)**

I do not see the issue when running on iOS 13 but see the issue for iOS 14

**Comment by 1024jp** [comment]
This issue was closed because it has been inactive for years since the last update and may be outdated. Please post a new comment if you still have an issue.
