### ISSUE TITLE
Does this library plan to support Privacy manifests?

### ISSUE THREAD

**Issue by mm-hirosawa** [1024jp/GzipSwift#62]
Hi,

Starting this April, all apps will need to be built with Xcode 15.
Along with that, the privacy manifest will need to be compatible as you know.
Does the GzipSwift also need to support privacy manifests?

Best,

**Comment by 1024jp** [comment]
GzipSwift does not access to any privacy information.
And I suppose, such packages don't need to have privacy manifests.

cf. [IS PrivacyManifest.xcprivacy still required for Framework even if no privacy accessed API is used?](https://forums.developer.apple.com/forums/thread/746481)

**Comment by mm-hirosawa** [comment]
Great. Thank you in advance.
